name: Deploy to Koyeb

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: ${{ secrets.KOYEB_API_TOKEN }}
      - name: Build and deploy to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          app-name: zahran-eshop
          service-name: zahran-eshop
          service-ports: "8080:http"
          service-routes: "/:8080"
          git-builder: docker
